# Generated by Django 5.0.6 on 2025-09-11 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('agency', models.CharField(blank=True, max_length=200)),
                ('offense_type', models.CharField(blank=True, max_length=200)),
                ('bond_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=200)),
                ('county', models.CharField(blank=True, max_length=200)),
                ('charge', models.CharField(blank=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='core.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='core.tenant')),
            ],
        ),
    ]
