# Generated by Django 5.0.6 on 2025-09-11 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_courtdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(choices=[('phone', 'Phone'), ('online', 'Online'), ('in_person', 'In-person')], default='in_person', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
