# Generated by Django 5.0.6 on 2025-09-11 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoice_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
