# Generated by Django 5.0.6 on 2025-09-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentplan_planinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtdate',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
