# Generated by Django 5.0.6 on 2025-09-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_courtdate_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('charge', 'Charge'), ('county', 'County'), ('offense_type', 'Offense Type'), ('jurisdiction', 'Jurisdiction')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'value'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
