# Generated by Django 5.0.6 on 2025-09-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lookupvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bond',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
