# Generated by Django 5.0.6 on 2025-09-14 01:22

from django.db import migrations

COUNTY_DEFAULTS = [
    "Guadalupe County Court at Law",
    "Guadalupe County District Court",
    "Comal County Court at Law",
    "Comal County District Court",
    "Bexar County Court at Law",
    "Bexar County District Court",
    "Hays County Court at Law",
    "Hays County District Court",
]

def seed_counties(apps, schema_editor):
    LookupValue = apps.get_model("core", "LookupValue")
    for name in COUNTY_DEFAULTS:
        LookupValue.objects.get_or_create(category="county", value=name)

def unseed_counties(apps, schema_editor):
    LookupValue = apps.get_model("core", "LookupValue")
    LookupValue.objects.filter(category="county", value__in=COUNTY_DEFAULTS).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bond_amount_bond_notes'),
    ]

    operations = [
    ]
