# Generated by Django 5.0.6 on 2025-09-19 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subs', to='core.person'),
        ),
    ]
